services:
  mariadb:
    image: mariadb:11.4.3-ubi9
    container_name: mariadb_service
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DEFAULT}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/static/tabelas.sql:/docker-entrypoint-initdb.d/tabelas.sql
    networks:
      - mariadb_network
    restart: always

  admin:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: nette
    networks:
      - mariadb_network

  erp:
    container_name: erp
    build: './'
    depends_on:
      - mariadb
    networks:
      - mariadb_network
    environment:
      DB_URL_LOCAL: ${DB_URL_LOCAL}
      DB_URL_DOCKER: ${DB_URL_DOCKER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL: ${MAIL}
      MAIL_PASS: ${MAIL_PASS}
    ports:
      - 8080:8080

volumes:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge
